### ISSUE TITLE
Реорганизовать структуру проекта

### ISSUE THREAD

**Issue by olinyavod** [olinyavod/MessageRouter#1]
Всё что кросс-платформенное вынести в namespace MessageRouter.Abstractions
Выделить отдельные реализации для разных платформ 
MessageRouter.Desktop
MessageRouer.Andriod
MessageRouter.iOS
MessageRouter.WInPhone

Отказываемся от использования Sockets for PCL и реализуем платформо зависимые части на самих платформах

**Comment by mesenev** [comment]
Частично сделано. Sockets решено пока оставить.
